### ISSUE TITLE
Travis builds failing (and 1.0.8 not published?)

### ISSUE THREAD

**Issue by gpgekko** [sbt/sbt-rjs#65]
Buffer overflows since 9 days:  https://travis-ci.org/sbt/sbt-rjs/builds

Not sure if it is related, but 1.0.8 doesn't seem to be available from the repositories either.

**Comment by huntc** [comment]
The 1.0.8 problem is now addressed. Apologies for any inconvenience caused.

**Comment by growak** [comment]
The build is still failing ... any progress on this issue ?
How can I be helpful ?

**Comment by benmccann** [comment]
This is fixed now. Sorry for the delay
